name: pushParkourStats
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - requests=2.31.0
  - pip=24.0
  - illumina-interop=1.3.1
  - pip:
      - interop==1.3.1