services:
  parkour2-convert-backup:
    container_name: parkour2-convert-backup
    image: postgres:latest
    env_file:
      - ./misc/parkour.env
    restart: always
    volumes:
      - ./misc/rsnapshot/backups/daily.0/localhost/data/parkour2_pgdb/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10

networks:
  parkour2:
    external: true