version: "3.5"

services:
  parkour2-postgres:
    container_name: parkour2-postgres
    image: postgres:latest
    env_file:
      - ./parkour.env
    restart: always
    volumes:
      - pgdb:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - 5432:5432

  parkour2-django:
    container_name: parkour2-django
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./parkour.env
    restart: always
    volumes:
      - ./parkour_app:/usr/src/app
      - media:/usr/src/app/media
      - staticfiles:/usr/src/app/staticfiles
    depends_on:
      parkour2-postgres:
        condition: service_healthy
    tty: false
    stdin_open: false
    # docker attach parkour2-django
    # Remember: Exit with ctrl+PQ (not C!!)

volumes:
  pgdb:
  media:
  staticfiles:

networks:
  default:
    name: parkour2_default
