name: Code Coverage

on:
  push:
    branches: [develop]
  pull_request:
    branches: [$default-branch]

jobs:
  pytest-cov:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r parkour_app/requirements/prod.txt
          awk '(NR>2)' parkour_app/requirements/testing.in | xargs pip install

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - name: Generate Report
        run: |
          sh -c 'pytest -n ${{ steps.cpu-cores.outputs.count }} \
            --cov-config=./parkour_app/.coveragerc \
            --cov=./parkour_app --cov-report=xml --cov-fail-under=0; \
              ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true