name: Stalebot

on:
  workflow_dispatch:
  schedule:
    # Everyday, 3:30 AM (Berlin)
    - cron: "30 1 * * *"

jobs:
  stalebot:
    if: github.repository == 'maxplanck-ie/parkour2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Close Stale Issues
        uses: actions/stale@v9.0.0
        permissions:
          contents: write
          issues: write
          pull-requests: write
        inputs:
          exempt-all-assigne: true
          days-before-pr-stale: 3
          days-before-pr-close: 2
          days-before-issue-stale: 120
          days-before-issue-close: 60
          only-pr-labels: 'Dependencies'
          
          
          
